export const baseUsers = [
  {
    email: 'axrorbek@gmail.com',
    username: 'axrorbek1997',
    first_name: 'Axrorbek',
    last_name: 'Jurayev',
    middle_name: '',
    isSeller: false,
    password: '123123',
  },
  {
    email: 'elchin@gmail.com',
    username: 'elchin2007',
    first_name: 'Elchin',
    last_name: 'Xudoyberganov',
    middle_name: '',
    isSeller: false,
    password: '123123',
  },
  {
    email: 'okhun@gmail.com',
    username: 'okhun1997',
    first_name: 'Okhun',
    last_name: 'Okhunov',
    middle_name: '',
    isSeller: false,
    password: '123123',
  },
  {
    email: 'shahzod@gmail.com',
    username: 'shahzod1997',
    first_name: 'Shahzod',
    last_name: 'Namazbaev',
    middle_name: '',
    isSeller: false,
    password: '123123',
  },
  {
    email: 'sirojiddin@gmail.com',
    username: 'ismailof',
    first_name: 'Sirojiddin',
    last_name: 'Ismoilov',
    middle_name: '',
    isSeller: true,
    password: '123123',
  },
];
